Added test for error condition so failure could be detected by hudson.

diff --git a/tests/rule-tests/Makefile b/tests/rule-tests/Makefile
--- a/tests/rule-tests/Makefile
+++ b/tests/rule-tests/Makefile
@@ -55,6 +55,7 @@ runRuleTestsNoCheck:
 	@for file in *.f03 ; do \
            echo "Running test $$file"; \
            $(JAVA) fortran.ofp.FrontEnd $$file; \
+           if [ $$? != 0 ]; then echo "FAILED while running test $$file"; exit 1; fi \
         done;
 
 clean:
