Add a target to caf_2.0 tests makefile to print a failure message for each test that fails. The other OFP test directories could benefit from this as well.

diff --git a/tests/caf_2.0/Makefile b/tests/caf_2.0/Makefile
--- a/tests/caf_2.0/Makefile
+++ b/tests/caf_2.0/Makefile
@@ -24,7 +24,14 @@ PARDIR=../
 FLAGS=--RiceCAF 
 #FLAGS=--RiceCAF --dump
 
-all: runRuleTestsNoCheck
+all: runRuleTestsCheck
+
+runRuleTestsCheck:
+	@for file in *.caf ; do \
+           echo "Running test $$file"; \
+           $(JAVA) fortran.ofp.FrontEnd $(FLAGS) --verbose $$file | grep -q "Parser exiting normally" ; rc=$$? ; \
+           if [ $$rc != 0 ]; then echo "...$$file FAILED!"; fi \
+        done;
 
 runRuleTestsNoCheck:
 	@for file in *.caf ; do \
